### PR TITLE
Assume 90 degree Earth avoidance for LyAl background

### PR DESCRIPTION
**Pull request by mcoughlin**
Brian request: Assume 90 degree Earth avoidance for LyAl background

### CODE REVIEW

**Comment by lpsinger** [comment]
That's a very large Earth avoidance angle. It will cut out half the sky. Are you sure about this?

By "LyAl", do you mean Lyman alpha? Why is this a concern, and why is it related to the Earth limb angle?

For Dorado's Earth limb, we are only worried about airglow.

**Comment by lpsinger** [comment]
Also would you please put a bullet point in the docstring to explain the value for the Earth avoidance angle?

**Comment by lpsinger** [comment]
Ahh, I see... From the [HST STIS handbook(https://hst-docs.stsci.edu/stisihb/chapter-6-exposure-time-calculations/6-5-detector-and-sky-backgrounds):

> Background due to geocoronal emission originates mainly from hydrogen and oxygen atoms in the exosphere of the Earth. The emission is concentrated in a very few lines. The brightest line is Lyman-α at 1216 Å.

(Dorado doesn't worry about Lyman alpha because it is outside our bandpass, so now I understand where the concern is coming from for UVEX.)

@bwgref, would you please confirm this 90° number? Does this apply at all times, or only during orbit day?

**Comment by bwgref** [comment]
Correct. There's a whole research thread by Shri here about the intensity of the 1216 AA line with respect to the Earth limb. But an important caveat is that this is an "enhanced background" limit, not a "we can't point the spacecraft here" limit for ToOs. For the all-sky survey we'd preferentially avoid this part of the sky to get the deepest observations. 

For Dorado since you've got refractive optics you already kill off all of the 1216 emission anyways and you only care about the oxygen lines. For UVEX we're above the residual atmosphere, so we don't care about the oxygen lines.

**Comment by lpsinger** [comment]
@bwgref, what about the other part of this question: do you want different sun avoidance angles for orbit day and orbit night, as we have for the Dorado configuration?

**Comment by bwgref** [comment]
@lpsinger No. Since UVEX is in HEO, we don't experience the orbit day/night transitions like in LEO. So our eclipses are rare and usually only a few hours long.

**Review by lpsinger — APPROVED** [review]

**Pull request merged**
