### PR TITLE
Factor orbit, FOV, and observing constraints into new Mission class

### PR DESCRIPTION
**Pull request by lpsinger**
I am not sure if this is the right abstraction, but at least it makes it so that the Dorado observing constraints are not in the one global visibility_constraints list.

@mcoughlin, could you see using this new Mission class?

### CODE REVIEW

**Review by mcoughlin — COMMENTED** [review]
Looks really nice. And I do like the python configurations.

We should also enable turning roll on or off perhaps? For now, I was solving with no roll.

**Comment by lpsinger** [comment]
> Looks really nice. And I do like the python configurations.

This doesn't use the Astropy configuration system. This just introduces a new class.

Can you see using this in the UVEX scripts?

> We should also enable turning roll on or off perhaps? For now, I was solving with no roll.

For now, since Dorado hasn't decided whether or not to vary roll angles, I am thinking of the roll grid as a command line option. If you pass a roll step size of 90 degrees, that has the same effect as turning off the roll grid.

**Comment by mcoughlin** [comment]
Yes. I suppose just slight annoyance if you want to update mission constraints needing to modify repository, but I think it's fine.

**Comment by lpsinger** [comment]
> Yes. I suppose just slight annoyance if you want to update mission constraints needing to modify repository, but I think it's fine.

Fair point. I'll whip up an example of what the Astropy configuration system implementation would look like.

**Comment by lpsinger** [comment]
I couldn't get the Astropy configuration system to work. I think it has to do with our module being called `dorado.scheduling` rather than `dorado_scheduling`. Can we adopt the Mission class as simply an incremental improvement?

**Comment by mcoughlin** [comment]
definitely better than nothing!

**Pull request merged**
