### PR TITLE
Refactor and clean up GROWTH tiling schemes

### PR DESCRIPTION
**Pull request by lpsinger**
Refactor and clean up GROWTH tiling schemes

- Move functions to the dorado.scheduling.tesselation module.
- Clean up existing GROWTH methods.
- Update all methods to take a single resolution parameter, area.
- Convert docstrings to Numpydoc format.
- Add example code.
- Add to Sphinx project documentation.
- Use Astropy quantities for angle arguments.
- Write output in ECSV format.
- Remove logger.

### CODE REVIEW

**Comment by lpsinger** [comment]
@mcoughlin, I would like to unify the options for all three tiling methods (the geodesic tiling and the two spiral tilings). The geodesic tiling has one natural argument: the desired number of tiles. The reason that this is the natural argument is that it allows only certain integer values, and it must solve for the actual number of tiles given the requested *minimum* number of tiles.

The other two tilings take two arguments (fov, scale), but both of those arguments really control the average areal density of the tiles.

What would be the most natural argument(s) for all three tilings to take?

**Comment by mcoughlin** [comment]
@lpsinger The "scale" term is redundant and a holdover from using the FOV in the config files. I do think something equivalent to "spacing between tiles" is what we are after in the end.

**Comment by lpsinger** [comment]
OK, then how about number of tiles, so that it's dimensionless?

**Comment by mcoughlin** [comment]
My only concern is that people may not intuitively know how to calculate the number of tiles for a given FOV. Do we provide them some guidance maybe?

**Comment by lpsinger** [comment]
So maybe area per tile is better?

**Comment by mcoughlin** [comment]
yes that sounds good to me.

**Comment by lpsinger** [comment]
The `phi_theta_spiral` method is misnamed, isn't it? It's just a regular grid on a Lambert projection, that is to say, a regular grid in right ascension and cosine declination?

**Comment by lpsinger** [comment]
I misspoke. The `phi_theta_spiral` is just a uniform grid on a [sinusoidal projection](https://en.wikipedia.org/wiki/Sinusoidal_projection), right, @mcoughlin?

**Comment by mcoughlin** [comment]
Yes this is more accurate.

**Comment by lpsinger** [comment]
@mcoughlin, I've updated all of the methods to take an area parameter.

Please review both the golden angle spiral and the sinusoidal grid methods. I have reimplemented them to make the code more transparent.

**Review by mcoughlin — APPROVED** [review]
Really love this Leo. Will be great for the users.

**Comment by lpsinger** [comment]
Great! FYI I made some small changes to the indexing in the sinusoidal routine, to improve handling of the boundaries in ra and dec.

**Pull request merged**
